filebeat.inputs:
- type: log
  paths:
  - '/var/log/trader/trader.json'
  json.fields_under_Root: true
  json.ignore_decoding_error: true
  tags: ["trader"]

output.elasticsearch:
  hosts: "elasticsearch:9200"
  index: "trader-%{+yyy.MM.dd}"
  pipeline: "trader_log_pipeline"

setup.ilm.enabled: false
setup.template.name: "trader"
setup.template.pattern: "trader-*"

ssl.verification_mode: "none"